# Project Euler # 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Written by Sam Gordon
# 09/15/12
# hikkakaru@gmail.com

total_int = 0

def Fib():
    a,b = 0,1
    yield a
    yield b
    while True:
        a,b = b,a+b
        yield b


def SubFib(startNumber, endNumber):
    for cur in Fib():
        if cur>endNumber: return
        if cur>=startNumber:
            yield cur

for i in SubFib(1,4000000):
    if i%2 == 0:
        total_int += i
        if total_int > 2000000:
            print(total_int)
